from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QEasingCurve, QPropertyAnimation, QVariant, QVariantAnimation, pyqtSlot
from PyQt5.QtGui import QColor, QPalette, QFontDatabase
from PyQt5.QtWidgets import QGraphicsOpacityEffect, QLabel

import font_resources

class AnimationLabel(QLabel):
    def __init__(self, *args, **kwargs):
        QLabel.__init__(self, *args, **kwargs)
        self.animation = QVariantAnimation()
        self.animation.valueChanged.connect(self.changeColor)

    @pyqtSlot(QVariant)
    def changeColor(self, color):
        palette = self.palette()
        palette.setColor(QPalette.WindowText, color)
        self.setPalette(palette)

    def startFadeIn(self):
        self.animation.stop()
        self.animation.setStartValue(QColor(255, 255, 255, 0))
        self.animation.setEndValue(QColor(255, 255, 255, 255))
        self.animation.setDuration(750)
        self.animation.setEasingCurve(QEasingCurve.InBack)
        self.animation.start()

    def startFadeInImage(self):
        self.effect = QGraphicsOpacityEffect()
        self.setGraphicsEffect(self.effect)

        self.animation = QPropertyAnimation(self.effect, b"opacity")
        self.animation.setDuration(200)
        self.animation.setStartValue(0)
        self.animation.setEndValue(1)
        self.animation.start()

    def startFadeOutImage(self):
        self.effect = QGraphicsOpacityEffect()
        self.setGraphicsEffect(self.effect)

        self.animation = QPropertyAnimation(self.effect, b"opacity")
        self.animation.setDuration(200)
        self.animation.setStartValue(1)
        self.animation.setEndValue(0)
        self.animation.start()


class Ui_StartDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(361, 186)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(8)
        Dialog.setFont(font)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setFormAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.formLayout.setHorizontalSpacing(10)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ok_button = QtWidgets.QPushButton(Dialog)
        self.ok_button.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.ok_button)
        self.exit_button = QtWidgets.QPushButton(Dialog)
        self.exit_button.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.exit_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Начало игры"))
        self.label.setText(_translate("Dialog", "Введите ваше имя:"))
        self.ok_button.setText(_translate("Dialog", "Начать игру"))
        self.exit_button.setText(_translate("Dialog", "Выйти"))


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        fontId = QFontDatabase.addApplicationFont(":itc_conduit.ttf")
        if fontId == 0:
            fontName = QFontDatabase.applicationFontFamilies(fontId)[0]
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 705)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.questionField = QtWidgets.QWidget(self.centralwidget)
        self.questionField.setGeometry(QtCore.QRect(0, 477, 1100, 201))
        self.questionField.setObjectName("questionField")
        self.answer_B = AnimationLabel(self.questionField)
        self.answer_B.setGeometry(QtCore.QRect(605, 100, 318, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.answer_B.setPalette(palette)
        font = QtGui.QFont(fontName)
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.answer_B.setFont(font)
        self.answer_B.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_B.setText("")
        self.answer_B.setAlignment(QtCore.Qt.AlignLeading |
                                   QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.answer_B.setWordWrap(True)
        self.answer_B.setObjectName("answer_B")
        self.answer_D = AnimationLabel(self.questionField)
        self.answer_D.setGeometry(QtCore.QRect(605, 152, 318, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.answer_D.setPalette(palette)
        font = QtGui.QFont(fontName)
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.answer_D.setFont(font)
        self.answer_D.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_D.setText("")
        self.answer_D.setAlignment(QtCore.Qt.AlignLeading |
                                   QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.answer_D.setWordWrap(True)
        self.answer_D.setObjectName("answer_D")
        self.question = AnimationLabel(self.questionField)
        self.question.setGeometry(QtCore.QRect(180, 8, 742, 80))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.question.setPalette(palette)
        font = QtGui.QFont(fontName)
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.question.setFont(font)
        self.question.setText("")
        self.question.setAlignment(QtCore.Qt.AlignCenter)
        self.question.setWordWrap(True)
        self.question.setObjectName("question")
        self.answer_A = AnimationLabel(self.questionField)
        self.answer_A.setGeometry(QtCore.QRect(200, 100, 318, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.answer_A.setPalette(palette)
        font = QtGui.QFont(fontName)
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.answer_A.setFont(font)
        self.answer_A.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_A.setText("")
        self.answer_A.setAlignment(QtCore.Qt.AlignLeading |
                                   QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.answer_A.setWordWrap(True)
        self.answer_A.setObjectName("answer_A")
        self.current_state_q = AnimationLabel(self.questionField)
        self.current_state_q.setGeometry(QtCore.QRect(0, 8, 1102, 191))
        self.current_state_q.setText("")
        self.current_state_q.setScaledContents(True)
        self.current_state_q.setObjectName("current_state_q")
        self.layout_q = QtWidgets.QLabel(self.questionField)
        self.layout_q.setGeometry(QtCore.QRect(0, 8, 1102, 190))
        self.layout_q.setText("")
        self.layout_q.setPixmap(QtGui.QPixmap("images/question field/layout.png"))
        self.layout_q.setScaledContents(True)
        self.layout_q.setObjectName("layout_q")
        self.answer_C = AnimationLabel(self.questionField)
        self.answer_C.setGeometry(QtCore.QRect(200, 152, 318, 41))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.answer_C.setPalette(palette)
        font = QtGui.QFont(fontName)
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.answer_C.setFont(font)
        self.answer_C.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.answer_C.setText("")
        self.answer_C.setAlignment(QtCore.Qt.AlignLeading |
                                   QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.answer_C.setWordWrap(True)
        self.answer_C.setObjectName("answer_C")
        self.current_state_q_2 = AnimationLabel(self.questionField)
        self.current_state_q_2.setGeometry(QtCore.QRect(0, 8, 1102, 191))
        self.current_state_q_2.setText("")
        self.current_state_q_2.setScaledContents(True)
        self.current_state_q_2.setObjectName("current_state_q_2")
        self.current_state_q_3 = QtWidgets.QLabel(self.questionField)
        self.current_state_q_3.setGeometry(QtCore.QRect(0, 8, 1102, 191))
        self.current_state_q_3.setText("")
        self.current_state_q_3.setScaledContents(True)
        self.current_state_q_3.setObjectName("current_state_q_3")
        self.amount_q = QtWidgets.QLabel(self.questionField)
        self.amount_q.setGeometry(QtCore.QRect(127, 62, 850, 81))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.amount_q.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(33)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setKerning(True)
        self.amount_q.setFont(font)
        self.amount_q.setText("")
        self.amount_q.setAlignment(QtCore.Qt.AlignCenter)
        self.amount_q.setObjectName("amount_q")
        self.double_dip = AnimationLabel(self.questionField)
        self.double_dip.setGeometry(QtCore.QRect(518, 129, 66, 36))
        self.double_dip.setText("")
        self.double_dip.setPixmap(QtGui.QPixmap("images/double-dip.png"))
        self.double_dip.setScaledContents(True)
        self.double_dip.setObjectName("double_dip")
        self.layout_q.raise_()
        self.amount_q.raise_()
        self.current_state_q.raise_()
        self.current_state_q_2.raise_()
        self.current_state_q_3.raise_()
        self.question.raise_()
        self.answer_A.raise_()
        self.answer_B.raise_()
        self.answer_C.raise_()
        self.answer_D.raise_()
        self.double_dip.raise_()
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1101, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.moneyTree = QtWidgets.QWidget(self.layoutWidget)
        self.moneyTree.setObjectName("moneyTree")
        self.layout_t = QtWidgets.QLabel(self.moneyTree)
        self.layout_t.setGeometry(QtCore.QRect(0, 0, 411, 480))
        self.layout_t.setText("")
        self.layout_t.setPixmap(QtGui.QPixmap("images/money tree/layout.png"))
        self.layout_t.setScaledContents(True)
        self.layout_t.setObjectName("layout_t")
        self.current_state_t = QtWidgets.QLabel(self.moneyTree)
        self.current_state_t.setGeometry(QtCore.QRect(0, 0, 411, 480))
        self.current_state_t.setText("")
        self.current_state_t.setScaledContents(True)
        self.current_state_t.setObjectName("current_state_t")
        self.lost_change = AnimationLabel(self.moneyTree)
        self.lost_change.setGeometry(QtCore.QRect(0, 0, 411, 480))
        self.lost_change.setText("")
        self.lost_change.setPixmap(QtGui.QPixmap("images/money tree/lost_change.png"))
        self.lost_change.setScaledContents(True)
        self.lost_change.setObjectName("lost_change")
        self.lost_5050 = AnimationLabel(self.moneyTree)
        self.lost_5050.setGeometry(QtCore.QRect(0, 0, 411, 480))
        self.lost_5050.setText("")
        self.lost_5050.setPixmap(QtGui.QPixmap("images/money tree/lost_5050.png"))
        self.lost_5050.setScaledContents(True)
        self.lost_5050.setObjectName("lost_5050")
        self.lost_x2 = AnimationLabel(self.moneyTree)
        self.lost_x2.setGeometry(QtCore.QRect(0, 0, 411, 480))
        self.lost_x2.setText("")
        self.lost_x2.setPixmap(QtGui.QPixmap("images/money tree/lost_x2.png"))
        self.lost_x2.setScaledContents(True)
        self.lost_x2.setObjectName("lost_x2")
        self.horizontalLayout.addWidget(self.moneyTree)
        self.horizontalLayout.setStretch(0, 101)
        self.horizontalLayout.setStretch(1, 50)
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 1100, 680))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap("images/background.jpg"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.background.raise_()
        self.questionField.raise_()
        self.layoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 25))
        self.menubar.setObjectName("menubar")
        self.game_menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.game_menu.setFont(font)
        self.game_menu.setObjectName("game_menu")
        self.table_menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.table_menu.setFont(font)
        self.table_menu.setObjectName("table_menu")
        self.menu = QtWidgets.QMenu(self.table_menu)
        self.menu.setObjectName("menu")
        self.help_menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.help_menu.setFont(font)
        self.help_menu.setObjectName("help_menu")
        MainWindow.setMenuBar(self.menubar)
        self.new_game = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.new_game.setFont(font)
        self.new_game.setObjectName("new_game")
        self.close_game = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.close_game.setFont(font)
        self.close_game.setObjectName("close_game")
        self.open_table = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.open_table.setFont(font)
        self.open_table.setObjectName("open_table")
        self.about = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.about.setFont(font)
        self.about.setObjectName("about")
        self.action = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.action.setFont(font)
        self.action.setObjectName("action")
        self.clear_one = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.clear_one.setFont(font)
        self.clear_one.setObjectName("clear_one")
        self.clear_all = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.clear_all.setFont(font)
        self.clear_all.setObjectName("clear_all")
        self.sound_btn = QtWidgets.QAction(MainWindow)
        self.sound_btn.setCheckable(True)
        self.sound_btn.setChecked(True)
        self.sound_btn.setObjectName("sound_btn")
        self.game_menu.addAction(self.new_game)
        self.game_menu.addAction(self.close_game)
        self.game_menu.addSeparator()
        self.game_menu.addAction(self.sound_btn)
        self.menu.addAction(self.clear_one)
        self.menu.addAction(self.clear_all)
        self.table_menu.addAction(self.open_table)
        self.table_menu.addAction(self.menu.menuAction())
        self.help_menu.addAction(self.about)
        self.menubar.addAction(self.game_menu.menuAction())
        self.menubar.addAction(self.table_menu.menuAction())
        self.menubar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Кто хочет стать Миллионером?"))
        self.game_menu.setTitle(_translate("MainWindow", "Игра"))
        self.table_menu.setTitle(_translate("MainWindow", "Таблица результатов"))
        self.menu.setTitle(_translate("MainWindow", "Очистить"))
        self.help_menu.setTitle(_translate("MainWindow", "Помощь"))
        self.new_game.setText(_translate("MainWindow", "Начать новую игру"))
        self.close_game.setText(_translate("MainWindow", "Завершить игру"))
        self.open_table.setText(_translate("MainWindow", "Открыть"))
        self.about.setText(_translate("MainWindow", "О программе"))
        self.action.setText(_translate("MainWindow", "Удалить один результат"))
        self.clear_one.setText(_translate("MainWindow", "Удалить один результат"))
        self.clear_all.setText(_translate("MainWindow", "Удалить всё"))
        self.sound_btn.setText(_translate("MainWindow", "Звук"))


class Ui_Win(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вы — миллионер!"))
        self.label.setText(_translate("Dialog", "Поздравляем! Вы выиграли и стали миллионером!\n"
                                      "Ваш выигрыш составил заветные 3 000 000 руб!\n"
                                      "Начать новую игру?"))


class Ui_GameOver(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вы проиграли!"))
        self.label.setText(_translate("Dialog", "Вы проиграли! Правильный ответ: {0}.\n"
                                      "Ваш выигрыш составил {1} руб.\n"
                                      "Начать новую игру?"))


class Ui_ConfirmExit(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 140)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 341, 32))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(24, 20, 351, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Завершить игру?"))
        self.label.setText(_translate(
            "Dialog", "Действительно завершить текущую игру без сохранения?"))


class Ui_ConfirmLeave(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(400, 140)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 341, 32))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(24, 20, 351, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Покинуть игру?"))
        self.label.setText(_translate(
            "Dialog", "Вы действительно хотите покинуть игру с суммой в {} руб?"))


class Ui_WinLeave(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Вы выиграли, но не всё!"))
        self.label.setText(_translate("Dialog", 
                                      "Вы покинули эту игру! Правильный ответ на этот вопрос: {0}.\n"
                                      "Ваш выигрыш составил {1} руб.\n"
                                      "Начать новую игру?"))


class Ui_ConfirmAgain(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setFixedSize(400, 140)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 341, 32))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(24, 20, 351, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Начать новую игру?"))
        self.label.setText(_translate(
            "Dialog", "Действительно начать новую игру без сохранения текущей?"))


class Ui_ResultsTable(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 385)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Form.setFont(font)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.okButton = QtWidgets.QPushButton(Form)
        self.okButton.setObjectName("okButton")
        self.verticalLayout.addWidget(self.okButton)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Таблица результатов"))
        self.okButton.setText(_translate("Form", "ОК"))


class Ui_DeleteResult(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 385)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(Form)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.spinBox.setFont(font)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.deleteButton = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.verticalLayout.addWidget(self.deleteButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Удаление результата из таблицы"))
        self.label.setText(_translate("Form", "Выберите номер результата для удаления:"))
        self.deleteButton.setText(_translate(
            "Form", "Удалить (без подтверждений, сразу при нажатии)"))


class Ui_ConfirmClearAll(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 140)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        Dialog.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 90, 341, 32))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
            QtWidgets.QDialogButtonBox.No | QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(24, 20, 351, 50))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Очистить таблицу результатов?"))
        self.label.setText(_translate(
            "Dialog", "Действительно очистить всю таблицу результатов без возможности вернуть?"))


class Ui_About(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(380, 308)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.ruText = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.ruText.setFont(font)
        self.ruText.setScaledContents(False)
        self.ruText.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.ruText.setWordWrap(True)
        self.ruText.setObjectName("ruText")
        self.verticalLayout.addWidget(self.ruText)
        self.enText = QtWidgets.QLabel(Form)
        self.enText.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        font.setPointSize(9)
        self.enText.setFont(font)
        self.enText.setScaledContents(False)
        self.enText.setAlignment(QtCore.Qt.AlignHCenter | QtCore.Qt.AlignTop)
        self.enText.setWordWrap(True)
        self.enText.setObjectName("enText")
        self.verticalLayout.addWidget(self.enText)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ruButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruButton.sizePolicy().hasHeightForWidth())
        self.ruButton.setSizePolicy(sizePolicy)
        self.ruButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.ruButton.setFont(font)
        self.ruButton.setObjectName("ruButton")
        self.horizontalLayout.addWidget(self.ruButton)
        self.enButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enButton.sizePolicy().hasHeightForWidth())
        self.enButton.setSizePolicy(sizePolicy)
        self.enButton.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.enButton.setFont(font)
        self.enButton.setObjectName("enButton")
        self.horizontalLayout.addWidget(self.enButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.okButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("PT Sans")
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.verticalLayout_2.addWidget(self.okButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "О программе"))
        self.ruText.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Игра «Кто хочет стать Миллионером?»</span></p><p align=\"center\">Игра, написанная на Python и основанная на популярном интеллектуальном телешоу <br/>«Who Wants to Be a Millionaire?»</p><p align=\"center\">© Павел Овчинников, 2020</p></body></html>"))
        self.enText.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">The Game «Who Want to Be a Millionaire?»</span></p><p align=\"center\">The game was written on Python and based on popular intellectual TV show <br/>«Who Wants to Be a Millionaire?»</p><p align=\"center\">© Pavel Ovchinnikov, 2020</p></body></html>"))
        self.ruButton.setText(_translate("Form", "RU"))
        self.enButton.setText(_translate("Form", "EN"))
        self.okButton.setText(_translate("Form", "ОК"))
