from .ui_classes import (
    AnimationLabel,
    Ui_About,
    Ui_ConfirmAgain,
    Ui_ConfirmClearAll,
    Ui_ConfirmExit,
    Ui_ConfirmLeave,
    Ui_DeleteResult,
    Ui_GameOver,
    Ui_MainWindow,
    Ui_ResultsTable,
    Ui_Rules,
    Ui_StartDialog,
    Ui_Win,
    Ui_WinLeave,
)
